logfilepath: "./logs"
logbackupsize: !ENV ${PS_LOGBACKUPSIZE:10}
loglevel:  !ENV ${PS_LOGLEVEL:INFO}
cansendtelegram: !ENV ${PS_SENDTELEGRAM:True}
botkey: !ENV ${PS_BOTKEY}
chatid: !ENV ${PS_CHATID}
timezone: !ENV ${PS_TIMEZONE:Europe/rome}
db_path: !ENV ${PS_DBPATH:personal.db}